### ISSUE TITLE
layout refresh position of element  after node was added

### ISSUE THREAD

**Issue by kikki** [johnnyflinn/ngCytoscape#11]
Hello I have one problem. When I add new node or edge so cy moved all elements in init position.
Example: https://plnkr.co/edit/oUTVzMrIuAutK6siC4aP?p=preview
workflow--> 
(1) Button click "add element" 
(2) move element to new position
(3) Button click "add element"
(4) element reset position 

hope you can help me..

**Comment by johnnyflinn** [comment]
I'm sorry, but I don't understand your issue.  The plunker seems to have several errors so it's difficult for me to replicate.

**Comment by kikki** [comment]
Hello johnnyflinn thanks for answer,
hope this little Example works. 
https://plnkr.co/edit/ouccJsCAND0mFv1oJtKA?p=preview
(I use firefox 44.0)

**Comment by johnnyflinn** [comment]
Ah.  Yes, this was due to the default layout being run after elements were added.  I just changed it.  Just be aware that if no position is specified, all newly added nodes will stack at position x:0. y:0.
