### ISSUE TITLE
Graph changes not updated

### ISSUE THREAD

**Issue by atoftegaard** [johnnyflinn/ngCytoscape#18]
Hi
It seems changes to edges, are not reflected on the graph. When loading, the graph is drawn as expected, but later adding/removal of edges seem ignored.

I have tried extending the changes on the nodes object, as in the demo - without any luck. What could be the problem?

**Comment by johnnyflinn** [comment]
Not enough info.

**Comment by ericmarcos** [comment]
Same problem here:

```html
<cytoscape flex graph-elements="graph.elements" graph-layout="graph.layout" graph-style="graph.styles"></cytoscape>
<button ng-click="onClick()">Test</button>
{{graph.elements | json}}
```

```javascript
$scope.graph = {
  elements: [
    {'data':{'id':'1', 'name':'1'}},
    {'data':{'id':'2', 'name':'2'}},
    {'data':{'id':'3', 'name':'3'}},
    {'data':{'source': '1', 'target': '2'}},
    {'data':{'source': '2', 'target': '3'}}
  ],
  layout: {...},
  styles: [...]
};
$scope.onClick = function() {
  $scope.graph.elements.pop();
};
```

You'll see how the edges disappear from the canvas, but not the nodes, despite they're really removed from the elements array.

**Comment by johnnyflinn** [comment]
Elements should be an object map, not an array of objects.  I wanted to realign this directive more closely with Cytoscape's Array of Objects, like you posted, I just haven't gotten around to it.
