### ISSUE TITLE
Registering and using a cytoscape extension

### ISSUE THREAD

**Issue by enjoiful** [johnnyflinn/ngCytoscape#20]
I'm trying to use a layout extension, cytoscape-cola (https://github.com/cytoscape/cytoscape.js-cola) with ng-cytoscape.  I'm having trouble registering the layout -- is this possible with this angular wrapper?

**Comment by enjoiful** [comment]
Per the cytoscape docs (http://js.cytoscape.org/#extensions/api), to register an extension:
cytoscape( type, name, extension );

How can I access the cytoscape object from the angular wrapper?

**Comment by anvial** [comment]
And what is the answer?

**Comment by SanderBreivik** [comment]
Was this closed because a solution was found?
