### ISSUE TITLE
Problem using cytoscape extensions

### ISSUE THREAD

**Issue by lightsaber91** [johnnyflinn/ngCytoscape#22]
Hi I'm a university student from University of Rome Tor Vergata and I'm developing a project for my graduate.
I'm currently using ngCytoscape and I'm having problem importing extension such like cytoscape.js-cola (Here is the link https://github.com/cytoscape/cytoscape.js-cola).
Is possible to import these type of extensions using ngCytoscape? And if so, how can I do?
Thanks for your attention!

**Comment by johnnyflinn** [comment]
You have to add the extension js file after cytoscape.js, but before ngCytoscape.  Then just pass the  extension config object into ngCytoscape via the graph-layouts attribute.

See http://johnnyflinn.github.io/ngCytoscape/#/layouts

**Comment by SanderBreivik** [comment]
Would you mind explaining that in more detail @johnnyflinn ?
